/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ["../../packages/ui/src/**/*.{html,js,tsx,ts,jsx}"],
  safelist: [],
  darkMode: "false",
  theme: {
    extend: {
      fontFamily: {
        roboto: ["Roboto", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        xxs: ["0.625rem", "normal"],
      },
      zIndex: {
        popover: 50,
        "nav-bar": 100,
        "nav-bar-over": 101,
        takeover: 150,
        panel: 175,
        modal: 200,
        "modal-popover": 250,
        notification: 99999,
      },

      boxShadow: {
        "glow-xs": "0 0 5px 1px var(--tw-shadow-color)",
        "glow-sm": "0 0 10px 2px var(--tw-shadow-color)",
        "glow-md": "0 0 15px 3px var(--tw-shadow-color)",
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "2xs": "0 1px rgb(0 0 0 / 0.05)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        sidebar: "hsl(var(--sidebar))",
        "sidebar-foreground": "hsl(var(--sidebar-foreground))",
        "sidebar-border": "hsl(var(--sidebar-border))",
        "sidebar-primary": "hsl(var(--sidebar-primary))",
        "sidebar-primary-foreground": "hsl(var(--sidebar-primary-foreground))",
        "sidebar-accent": "hsl(var(--sidebar-accent))",
        "sidebar-accent-foreground": "hsl(var(--sidebar-accent-foreground))",
        "sidebar-ring": "hsl(var(--sidebar-ring))",
        background: "hsl(var(--background))",
        "dark-background": "hsl(var(--dark-background))",
        foreground: "hsl(var(--foreground))",
        "dark-foreground": "hsl(var(--dark-foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        // End of standard shadcn colors
        brand: {
          25: "rgba(var(--custom-colors-brand-25))",
          50: "rgba(var(--custom-colors-brand-50))",
          100: "rgba(var(--custom-colors-brand-100))",
          200: "rgba(var(--custom-colors-brand-200))",
          300: "rgba(var(--custom-colors-brand-300))",
          400: "rgba(var(--custom-colors-brand-400))",
          500: "rgba(var(--custom-colors-brand-500))",
          600: "rgba(var(--custom-colors-brand-600))",
          700: "rgba(var(--custom-colors-brand-700))",
          800: "rgba(var(--custom-colors-brand-800))",
          900: "rgba(var(--custom-colors-brand-900))",
          950: "rgba(var(--custom-colors-brand-950))",
        },
        success: {
          25: "rgba(var(--custom-colors-success-25))",
          50: "rgba(var(--custom-colors-success-50))",
          100: "rgba(var(--custom-colors-success-100))",
          200: "rgba(var(--custom-colors-success-200))",
          300: "rgba(var(--custom-colors-success-300))",
          400: "rgba(var(--custom-colors-success-400))",
          500: "rgba(var(--custom-colors-success-500))",
          600: "rgba(var(--custom-colors-success-600))",
          700: "rgba(var(--custom-colors-success-700))",
          800: "rgba(var(--custom-colors-success-800))",
          900: "rgba(var(--custom-colors-success-900))",
          950: "rgba(var(--custom-colors-success-950))",
        },
        error: {
          25: "rgba(var(--custom-colors-error-25))",
          50: "rgba(var(--custom-colors-error-50))",
          100: "rgba(var(--custom-colors-error-100))",
          200: "rgba(var(--custom-colors-error-200))",
          300: "rgba(var(--custom-colors-error-300))",
          400: "rgba(var(--custom-colors-error-400))",
          500: "rgba(var(--custom-colors-error-500))",
          600: "rgba(var(--custom-colors-error-600))",
          700: "rgba(var(--custom-colors-error-700))",
          800: "rgba(var(--custom-colors-error-800))",
          900: "rgba(var(--custom-colors-error-900))",
          950: "rgba(var(--custom-colors-error-950))",
        },
        warning: {
          25: "rgba(var(--custom-colors-warning-25))",
          50: "rgba(var(--custom-colors-warning-50))",
          100: "rgba(var(--custom-colors-warning-100))",
          200: "rgba(var(--custom-colors-warning-200))",
          300: "rgba(var(--custom-colors-warning-300))",
          400: "rgba(var(--custom-colors-warning-400))",
          500: "rgba(var(--custom-colors-warning-500))",
          600: "rgba(var(--custom-colors-warning-600))",
          700: "rgba(var(--custom-colors-warning-700))",
          800: "rgba(var(--custom-colors-warning-800))",
          900: "rgba(var(--custom-colors-warning-900))",
          950: "rgba(var(--custom-colors-warning-950))",
        },

        "gray-blue": {
          50: "rgba(var(--custom-colors-gray-blue-50))",
          100: "rgba(var(--custom-colors-gray-blue-100))",
          200: "rgba(var(--custom-colors-gray-blue-200))",
          300: "rgba(var(--custom-colors-gray-blue-300))",
          400: "rgba(var(--custom-colors-gray-blue-400))",
          500: "rgba(var(--custom-colors-gray-blue-500))",
          600: "rgba(var(--custom-colors-gray-blue-600))",
          700: "rgba(var(--custom-colors-gray-blue-700))",
          800: "rgba(var(--custom-colors-gray-blue-800))",
          900: "rgba(var(--custom-colors-gray-blue-900))",
          950: "rgba(var(--custom-colors-gray-blue-950))",
        },
        "gray-cool": {
          50: "rgba(var(--custom-colors-gray-cool-50))",
          100: "rgba(var(--custom-colors-gray-cool-100))",
          200: "rgba(var(--custom-colors-gray-cool-200))",
          300: "rgba(var(--custom-colors-gray-cool-300))",
          400: "rgba(var(--custom-colors-gray-cool-400))",
          500: "rgba(var(--custom-colors-gray-cool-500))",
          600: "rgba(var(--custom-colors-gray-cool-600))",
          700: "rgba(var(--custom-colors-gray-cool-700))",
          800: "rgba(var(--custom-colors-gray-cool-800))",
          900: "rgba(var(--custom-colors-gray-cool-900))",
          950: "rgba(var(--custom-colors-gray-cool-950))",
        },
        "gray-neutral": {
          100: "rgba(var(--custom-colors-gray-neutral-100))",
          200: "rgba(var(--custom-colors-gray-neutral-200))",
          300: "rgba(var(--custom-colors-gray-neutral-300))",
          400: "rgba(var(--custom-colors-gray-neutral-400))",
          500: "rgba(var(--custom-colors-gray-neutral-500))",
          600: "rgba(var(--custom-colors-gray-neutral-600))",
          700: "rgba(var(--custom-colors-gray-neutral-700))",
          800: "rgba(var(--custom-colors-gray-neutral-800))",
          900: "rgba(var(--custom-colors-gray-neutral-900))",
          950: "rgba(var(--custom-colors-gray-neutral-950))",
        },
        "gray-iron": {
          25: "rgba(var(--custom-colors-gray-iron-25))",
          50: "rgba(var(--custom-colors-gray-iron-50))",
          100: "rgba(var(--custom-colors-gray-iron-100))",
          200: "rgba(var(--custom-colors-gray-iron-200))",
          300: "rgba(var(--custom-colors-gray-iron-300))",
          400: "rgba(var(--custom-colors-gray-iron-400))",
          500: "rgba(var(--custom-colors-gray-iron-500))",
          600: "rgba(var(--custom-colors-gray-iron-600))",
          700: "rgba(var(--custom-colors-gray-iron-700))",
          800: "rgba(var(--custom-colors-gray-iron-800))",
          900: "rgba(var(--custom-colors-gray-iron-900))",
          950: "rgba(var(--custom-colors-gray-iron-950))",
        },
        "gray-true": {
          50: "rgba(var(--custom-colors-gray-true-50))",
          100: "rgba(var(--custom-colors-gray-true-100))",
          200: "rgba(var(--custom-colors-gray-true-200))",
          300: "rgba(var(--custom-colors-gray-true-300))",
          400: "rgba(var(--custom-colors-gray-true-400))",
          500: "rgba(var(--custom-colors-gray-true-500))",
          600: "rgba(var(--custom-colors-gray-true-600))",
          700: "rgba(var(--custom-colors-gray-true-700))",
          800: "rgba(var(--custom-colors-gray-true-800))",
          900: "rgba(var(--custom-colors-gray-true-900))",
          950: "rgba(var(--custom-colors-gray-true-950))",
        },
        "gray-warm": {
          25: "rgba(var(--custom-colors-gray-warm-25))",
          50: "rgba(var(--custom-colors-gray-warm-50))",
          100: "rgba(var(--custom-colors-gray-warm-100))",
          200: "rgba(var(--custom-colors-gray-warm-200))",
          300: "rgba(var(--custom-colors-gray-warm-300))",
          400: "rgba(var(--custom-colors-gray-warm-400))",
          500: "rgba(var(--custom-colors-gray-warm-500))",
          600: "rgba(var(--custom-colors-gray-warm-600))",
          700: "rgba(var(--custom-colors-gray-warm-700))",
          800: "rgba(var(--custom-colors-gray-warm-800))",
          900: "rgba(var(--custom-colors-gray-warm-900))",
          950: "rgba(var(--custom-colors-gray-warm-950))",
        },
        moss: {
          25: "rgba(var(--custom-colors-moss-25))",
          50: "rgba(var(--custom-colors-moss-50))",
          100: "rgba(var(--custom-colors-moss-100))",
          200: "rgba(var(--custom-colors-moss-200))",
          300: "rgba(var(--custom-colors-moss-300))",
          400: "rgba(var(--custom-colors-moss-400))",
          500: "rgba(var(--custom-colors-moss-500))",
          600: "rgba(var(--custom-colors-moss-600))",
          700: "rgba(var(--custom-colors-moss-700))",
          800: "rgba(var(--custom-colors-moss-800))",
          900: "rgba(var(--custom-colors-moss-900))",
          950: "rgba(var(--custom-colors-moss-950))",
        },
        "green-light": {
          25: "rgba(var(--custom-colors-green-light-25))",
          50: "rgba(var(--custom-colors-green-light-50))",
          100: "rgba(var(--custom-colors-green-light-100))",
          200: "rgba(var(--custom-colors-green-light-200))",
          300: "rgba(var(--custom-colors-green-light-300))",
          400: "rgba(var(--custom-colors-green-light-400))",
          500: "rgba(var(--custom-colors-green-light-500))",
          600: "rgba(var(--custom-colors-green-light-600))",
          700: "rgba(var(--custom-colors-green-light-700))",
          800: "rgba(var(--custom-colors-green-light-800))",
          900: "rgba(var(--custom-colors-green-light-900))",
          950: "rgba(var(--custom-colors-green-light-950))",
        },

        "blue-light": {
          25: "rgba(var(--custom-colors-blue-light-25))",
          50: "rgba(var(--custom-colors-blue-light-50))",
          100: "rgba(var(--custom-colors-blue-light-100))",
          200: "rgba(var(--custom-colors-blue-light-200))",
          300: "rgba(var(--custom-colors-blue-light-300))",
          400: "rgba(var(--custom-colors-blue-light-400))",
          500: "rgba(var(--custom-colors-blue-light-500))",
          600: "rgba(var(--custom-colors-blue-light-600))",
          700: "rgba(var(--custom-colors-blue-light-700))",
          800: "rgba(var(--custom-colors-blue-light-800))",
          900: "rgba(var(--custom-colors-blue-light-900))",
          950: "rgba(var(--custom-colors-blue-light-950))",
        },

        "blue-dark": {
          25: "rgba(var(--custom-colors-blue-dark-25))",
          50: "rgba(var(--custom-colors-blue-dark-50))",
          100: "rgba(var(--custom-colors-blue-dark-100))",
          200: "rgba(var(--custom-colors-blue-dark-200))",
          300: "rgba(var(--custom-colors-blue-dark-300))",
          400: "rgba(var(--custom-colors-blue-dark-400))",
          500: "rgba(var(--custom-colors-blue-dark-500))",
          600: "rgba(var(--custom-colors-blue-dark-600))",
          700: "rgba(var(--custom-colors-blue-dark-700))",
          800: "rgba(var(--custom-colors-blue-dark-800))",
          900: "rgba(var(--custom-colors-blue-dark-900))",
          950: "rgba(var(--custom-colors-blue-dark-950))",
        },

        "orange-dark": {
          25: "rgba(var(--custom-colors-orange-dark-25))",
          50: "rgba(var(--custom-colors-orange-dark-50))",
          100: "rgba(var(--custom-colors-orange-dark-100))",
          200: "rgba(var(--custom-colors-orange-dark-200))",
          300: "rgba(var(--custom-colors-orange-dark-300))",
          400: "rgba(var(--custom-colors-orange-dark-400))",
          500: "rgba(var(--custom-colors-orange-dark-500))",
          600: "rgba(var(--custom-colors-orange-dark-600))",
          700: "rgba(var(--custom-colors-orange-dark-700))",
          800: "rgba(var(--custom-colors-orange-dark-800))",
          900: "rgba(var(--custom-colors-orange-dark-900))",
          950: "rgba(var(--custom-colors-orange-dark-950))",
        },

        border: {
          neutral: {
            primary: "rgba(var(--custom-colors-gray-neutral-200))",
            secondary: "rgba(var(--custom-colors-gray-neutral-300))",
            tertiary: "rgba(var(--custom-colors-gray-neutral-100))",
            quaternary: "rgba(var(--custom-colors-gray-neutral-400))",
            disabled: "rgba(var(--custom-colors-gray-neutral-200))",
            disabled_subtle: "rgba(var(--custom-colors-gray-neutral-100))",
            white: "rgba(var(--custom-colors-base-white))",
          },
          brand: {
            primary: "rgba(var(--custom-colors-blue-500))",
            secondary: "rgba(var(--custom-colors-blue-600))",
            tertiary: "rgba(var(--custom-colors-blue-200))",
            quaternary: "rgba(var(--custom-colors-blue-600))",
            quinary: "rgba(var(--custom-colors-blue-100))",
          },
          error: {
            primary: "rgba(var(--custom-colors-error-500))",
            secondary: "rgba(var(--custom-colors-error-200))",
            tertiary: "rgba(var(--custom-colors-error-600))",
            quaternary: "rgba(var(--custom-colors-error-100))",
          },
          success: {
            primary: "rgba(var(--custom-colors-success-500))",
            secondary: "rgba(var(--custom-colors-success-200))",
            tertiary: "rgba(var(--custom-colors-success-600))",
          },
          warning: {
            primary: "rgba(var(--custom-colors-warning-500))",
            secondary: "rgba(var(--custom-colors-warning-200))",
            tertiary: "rgba(var(--custom-colors-warning-600))",
            quaternary: "rgba(var(--custom-colors-warning-100))",
          },
        },
        text: {
          neutral: {
            primary: "rgba(var(--custom-colors-gray-modern-900))",
            "primary-on-brand": "rgba(var(--custom-colors-base-white))",
            secondary: "rgba(var(--custom-colors-gray-modern-700))",
            "secondary-hover": "rgba(var(--custom-colors-gray-modern-800))",
            tertiary: "rgba(var(--custom-colors-gray-modern-600))",
            "tertiary-hover": "rgba(var(--custom-colors-gray-700))",
            quaternary: "rgba(var(--custom-colors-gray-modern-500))",
            white: "rgba(var(--custom-colors-base-white))",
            "quinary-disabled": "rgba(var(--custom-colors-gray-modern-400))",
            placeholder: "rgba(var(--custom-colors-gray-modern-500))",
            "placeholder-subtle": "rgba(var(--custom-colors-gray-modern-300))",
          },

          brand: {
            secondary: "rgba(var(--custom-colors-blue-900))",
            primary: "rgba(var(--custom-colors-blue-700))",
            tertiary: "rgba(var(--custom-colors-blue-600))",
          },
          error: {
            primary: "rgba(var(--custom-colors-error-700))",
            secondary: "rgba(var(--custom-colors-error-600))",
          },
          warning: {
            primary: "rgba(var(--custom-colors-warning-600))",
          },
          success: {
            primary: "rgba(var(--custom-colors-success-700))",
            secondary: "rgba(var(--custom-colors-success-600))",
          },
        },
        icon: {
          brand: {
            primary: "rgba(var(--custom-colors-blue-700))",
            secondary: "rgba(var(--custom-colors-blue-600))",
            tertiary: "rgba(var(--custom-colors-blue-400))",
            quaternary: "rgba(var(--custom-colors-blue-800))",
          },
          neutral: {
            primary: "rgba(var(--custom-colors-gray-modern-900))",
            secondary: "rgba(var(--custom-colors-gray-modern-700))",
            tertiary: "rgba(var(--custom-colors-gray-modern-600))",
            quaternary: "rgba(var(--custom-colors-gray-modern-400))",
            quinary: "rgba(var(--custom-colors-gray-modern-500))",
            white: "rgba(var(--custom-colors-base-white))",
            placeholder: "rgba(var(--custom-colors-gray-modern-500))",
          },
          grayblue: "rgba(var(--custom-colors-gray-blue-700))",
          error: {
            primary: "rgba(var(--custom-colors-error-700))",
            secondary: "rgba(var(--custom-colors-error-600))",
            tertiary: "rgba(var(--custom-colors-error-400))",
          },
          warning: {
            primary: "rgba(var(--custom-colors-warning-700))",
            secondary: "rgba(var(--custom-colors-warning-600))",
            tertiary: "rgba(var(--custom-colors-warning-500))",
          },
          success: {
            primary: "rgba(var(--custom-colors-success-700))",
            secondary: "rgba(var(--custom-colors-success-600))",
            tertiary: "rgba(var(--custom-colors-success-500))",
          },
        },
        fg: {
          neutral: {
            primary: "rgba(var(--custom-colors-gray-modern-900))",
            secondary: "rgba(var(--custom-colors-gray-modern-700))",
            "secondary-hover": "rgba(var(--custom-colors-gray-modern-800))",
            tertiary: "rgba(var(--custom-colors-gray-modern-600))",
            "tertiary-hover": "rgba(var(--custom-colors-gray-modern-700))",
            quaternary: "rgba(var(--custom-colors-gray-modern-500))",
            "quaternary-hover": "rgba(var(--custom-colors-gray-modern-600))",
            quinary: "rgba(var(--custom-colors-gray-modern-400))",
            "quinary-hover": "rgba(var(--custom-colors-gray-modern-500))",
            senary: "rgba(var(--custom-colors-gray-modern-300))",
            septenary: "rgba(var(--custom-colors-gray-modern-50))",
            white: "rgba(var(--custom-colors-base-white))",
            disabled: "rgba(var(--custom-colors-gray-modern-100))",
          },
          brand: {
            primary: "rgba(var(--custom-colors-blue-600))",
            secondary: "rgba(var(--custom-colors-blue-700))",
            tertiary: "rgba(var(--custom-colors-blue-500))",
            quaternary: "rgba(var(--custom-colors-blue-50))",
            quinary: "rgba(var(--custom-colors-blue-100))",
          },
          error: {
            primary: "rgba(var(--custom-colors-error-600))",
            secondary: "rgba(var(--custom-colors-error-500))",
            tertiary: "rgba(var(--custom-colors-error-50))",
          },
          warning: {
            primary: "rgba(var(--custom-colors-warning-600))",
            secondary: "rgba(var(--custom-colors-warning-500))",
          },
          success: {
            primary: "rgba(var(--custom-colors-success-600))",
            secondary: "rgba(var(--custom-colors-success-500))",
          },
        },

        bg: {
          neutral: {
            primary: "rgba(var(--custom-colors-base-white))",
            secondary: "rgba(var(--custom-colors-gray-modern-25))",
            "secondary-hover": "rgba(var(--custom-colors-gray-modern-50))",
            "primary-solid": "rgba(var(--custom-colors-gray-modern-950))",
            tertiary: "rgba(var(--custom-colors-gray-modern-50))",
            quaternary: "rgba(var(--custom-colors-gray-modern-100))",
            quinary: "rgba(var(--custom-colors-gray-modern-200))",
            senary: "rgba(var(--custom-colors-gray-modern-50))",
            active: "rgba(var(--custom-colors-gray-modern-50))",
            disabled: "rgba(var(--custom-colors-gray-modern-100))",
            overlay: "rgba(var(--custom-colors-gray-modern-950))",
          },
          brand: {
            primary: "rgba(var(--custom-colors-blue-50))",
            "primary-hover": "rgba(var(--custom-colors-blue-100))",
            secondary: "rgba(var(--custom-colors-blue-100))",
            tertiary: "rgba(var(--custom-colors-blue-50))",
            solid: "rgba(var(--custom-colors-blue-600))",
            "solid-hover": "rgba(var(--custom-colors-blue-700))",
            section: "rgba(var(--custom-colors-blue-800))",
            section_subtle: "rgba(var(--custom-colors-blue-700))",
          },
          error: {
            primary: "rgba(var(--custom-colors-error-50))",
            secondary: "rgba(var(--custom-colors-error-100))",
            solid: "rgba(var(--custom-colors-error-600))",
          },
          warning: {
            primary: "rgba(var(--custom-colors-warning-50))",
            secondary: "rgba(var(--custom-colors-warning-100))",
            solid: "rgba(var(--custom-colors-warning-600))",
          },
          success: {
            primary: "rgba(var(--custom-colors-success-50))",
            secondary: "rgba(var(--custom-colors-success-100))",
            solid: "rgba(var(--custom-colors-success-600))",
          },
        },

        utility: {
          gray: {
            50: "rgba(var(--custom-colors-gray-50))",
            100: "rgba(var(--custom-colors-gray-100))",
            200: "rgba(var(--custom-colors-gray-200))",
            300: "rgba(var(--custom-colors-gray-300))",
            400: "rgba(var(--custom-colors-gray-400))",
            500: "rgba(var(--custom-colors-gray-500))",
            600: "rgba(var(--custom-colors-gray-600))",
            700: "rgba(var(--custom-colors-gray-700))",
            800: "rgba(var(--custom-colors-gray-800))",
            900: "rgba(var(--custom-colors-gray-900))",
          },
          brand: {
            50: "rgba(var(--custom-colors-blue-50))",
            100: "rgba(var(--custom-colors-blue-100))",
            200: "rgba(var(--custom-colors-blue-200))",
            300: "rgba(var(--custom-colors-blue-300))",
            400: "rgba(var(--custom-colors-blue-400))",
            500: "rgba(var(--custom-colors-blue-500))",
            600: "rgba(var(--custom-colors-blue-600))",
            700: "rgba(var(--custom-colors-blue-700))",
            800: "rgba(var(--custom-colors-blue-800))",
            900: "rgba(var(--custom-colors-blue-900))",
          },
          error: {
            50: "rgba(var(--custom-colors-error-50))",
            100: "rgba(var(--custom-colors-error-100))",
            200: "rgba(var(--custom-colors-error-200))",
            300: "rgba(var(--custom-colors-error-300))",
            400: "rgba(var(--custom-colors-error-400))",
            500: "rgba(var(--custom-colors-error-500))",
            600: "rgba(var(--custom-colors-error-600))",
            700: "rgba(var(--custom-colors-error-700))",
            800: "rgba(var(--custom-colors-error-800))",
            900: "rgba(var(--custom-colors-error-900))",
          },
          warning: {
            50: "rgba(var(--custom-colors-warning-50))",
            100: "rgba(var(--custom-colors-warning-100))",
            200: "rgba(var(--custom-colors-warning-200))",
            300: "rgba(var(--custom-colors-warning-300))",
            400: "rgba(var(--custom-colors-warning-400))",
            500: "rgba(var(--custom-colors-warning-500))",
            600: "rgba(var(--custom-colors-warning-600))",
            700: "rgba(var(--custom-colors-warning-700))",
            800: "rgba(var(--custom-colors-warning-800))",
            900: "rgba(var(--custom-colors-warning-900))",
          },
          success: {
            50: "rgba(var(--custom-colors-success-50))",
            100: "rgba(var(--custom-colors-success-100))",
            200: "rgba(var(--custom-colors-success-200))",
            300: "rgba(var(--custom-colors-success-300))",
            400: "rgba(var(--custom-colors-success-400))",
            500: "rgba(var(--custom-colors-success-500))",
            600: "rgba(var(--custom-colors-success-600))",
            700: "rgba(var(--custom-colors-success-700))",
            800: "rgba(var(--custom-colors-success-800))",
            900: "rgba(var(--custom-colors-success-900))",
            950: "rgba(var(--custom-colors-success-950))",
          },
          "gray-blue": {
            50: "rgba(var(--custom-colors-gray-blue-50))",
            100: "rgba(var(--custom-colors-gray-blue-100))",
            200: "rgba(var(--custom-colors-gray-blue-200))",
            300: "rgba(var(--custom-colors-gray-blue-300))",
            400: "rgba(var(--custom-colors-gray-blue-400))",
            500: "rgba(var(--custom-colors-gray-blue-500))",
            600: "rgba(var(--custom-colors-gray-blue-600))",
            700: "rgba(var(--custom-colors-gray-blue-700))",
            800: "rgba(var(--custom-colors-gray-blue-800))",
            900: "rgba(var(--custom-colors-gray-blue-900))",
            950: "rgba(var(--custom-colors-gray-blue-950))",
          },
          green: {
            50: "rgba(var(--custom-colors-green-50))",
            100: "rgba(var(--custom-colors-green-100))",
            200: "rgba(var(--custom-colors-green-200))",
            300: "rgba(var(--custom-colors-green-300))",
            400: "rgba(var(--custom-colors-green-400))",
            500: "rgba(var(--custom-colors-green-500))",
            600: "rgba(var(--custom-colors-green-600))",
            700: "rgba(var(--custom-colors-green-700))",
            800: "rgba(var(--custom-colors-green-800))",
            900: "rgba(var(--custom-colors-green-900))",
            950: "rgba(var(--custom-colors-green-950))",
          },
          "blue-light": {
            50: "rgba(var(--custom-colors-blue-light-50))",
            100: "rgba(var(--custom-colors-blue-light-100))",
            200: "rgba(var(--custom-colors-blue-light-200))",
            300: "rgba(var(--custom-colors-blue-light-300))",
            400: "rgba(var(--custom-colors-blue-light-400))",
            500: "rgba(var(--custom-colors-blue-light-500))",
            600: "rgba(var(--custom-colors-blue-light-600))",
            700: "rgba(var(--custom-colors-blue-light-700))",
            800: "rgba(var(--custom-colors-blue-light-800))",
            900: "rgba(var(--custom-colors-blue-light-900))",
            950: "rgba(var(--custom-colors-blue-light-950))",
          },
          blue: {
            50: "rgba(var(--custom-colors-blue-50))",
            100: "rgba(var(--custom-colors-blue-100))",
            200: "rgba(var(--custom-colors-blue-200))",
            300: "rgba(var(--custom-colors-blue-300))",
            400: "rgba(var(--custom-colors-blue-400))",
            500: "rgba(var(--custom-colors-blue-500))",
            600: "rgba(var(--custom-colors-blue-600))",
            700: "rgba(var(--custom-colors-blue-700))",
            800: "rgba(var(--custom-colors-blue-800))",
            900: "rgba(var(--custom-colors-blue-900))",
            950: "rgba(var(--custom-colors-blue-950))",
          },
          "blue-dark": {
            50: "rgba(var(--custom-colors-blue-dark-50))",
            100: "rgba(var(--custom-colors-blue-dark-100))",
            200: "rgba(var(--custom-colors-blue-dark-200))",
            300: "rgba(var(--custom-colors-blue-dark-300))",
            400: "rgba(var(--custom-colors-blue-dark-400))",
            500: "rgba(var(--custom-colors-blue-dark-500))",
            600: "rgba(var(--custom-colors-blue-dark-600))",
            700: "rgba(var(--custom-colors-blue-dark-700))",
            800: "rgba(var(--custom-colors-blue-dark-800))",
            900: "rgba(var(--custom-colors-blue-dark-900))",
            950: "rgba(var(--custom-colors-blue-dark-950))",
          },
          indigo: {
            50: "rgba(var(--custom-colors-indigo-50))",
            100: "rgba(var(--custom-colors-indigo-100))",
            200: "rgba(var(--custom-colors-indigo-200))",
            300: "rgba(var(--custom-colors-indigo-300))",
            400: "rgba(var(--custom-colors-indigo-400))",
            500: "rgba(var(--custom-colors-indigo-500))",
            600: "rgba(var(--custom-colors-indigo-600))",
            700: "rgba(var(--custom-colors-indigo-700))",
            800: "rgba(var(--custom-colors-indigo-800))",
            900: "rgba(var(--custom-colors-indigo-900))",
            950: "rgba(var(--custom-colors-indigo-950))",
          },
          purple: {
            50: "rgba(var(--custom-colors-purple-50))",
            100: "rgba(var(--custom-colors-purple-100))",
            200: "rgba(var(--custom-colors-purple-200))",
            300: "rgba(var(--custom-colors-purple-300))",
            400: "rgba(var(--custom-colors-purple-400))",
            500: "rgba(var(--custom-colors-purple-500))",
            600: "rgba(var(--custom-colors-purple-600))",
            700: "rgba(var(--custom-colors-purple-700))",
            800: "rgba(var(--custom-colors-purple-800))",
            900: "rgba(var(--custom-colors-purple-900))",
          },
          fuchsia: {
            50: "rgba(var(--custom-colors-fuchsia-50))",
            100: "rgba(var(--custom-colors-fuchsia-100))",
            200: "rgba(var(--custom-colors-fuchsia-200))",
            300: "rgba(var(--custom-colors-fuchsia-300))",
            400: "rgba(var(--custom-colors-fuchsia-400))",
            500: "rgba(var(--custom-colors-fuchsia-500))",
            600: "rgba(var(--custom-colors-fuchsia-600))",
            700: "rgba(var(--custom-colors-fuchsia-700))",
            800: "rgba(var(--custom-colors-fuchsia-800))",
            900: "rgba(var(--custom-colors-fuchsia-900))",
          },
          pink: {
            50: "rgba(var(--custom-colors-pink-50))",
            100: "rgba(var(--custom-colors-pink-100))",
            200: "rgba(var(--custom-colors-pink-200))",
            300: "rgba(var(--custom-colors-pink-300))",
            400: "rgba(var(--custom-colors-pink-400))",
            500: "rgba(var(--custom-colors-pink-500))",
            600: "rgba(var(--custom-colors-pink-600))",
            700: "rgba(var(--custom-colors-pink-700))",
            800: "rgba(var(--custom-colors-pink-800))",
            900: "rgba(var(--custom-colors-pink-900))",
          },
          "orange-dark": {
            50: "rgba(var(--custom-colors-orange-dark-50))",
            100: "rgba(var(--custom-colors-orange-dark-100))",
            200: "rgba(var(--custom-colors-orange-dark-200))",
            300: "rgba(var(--custom-colors-orange-dark-300))",
            400: "rgba(var(--custom-colors-orange-dark-400))",
            500: "rgba(var(--custom-colors-orange-dark-500))",
            600: "rgba(var(--custom-colors-orange-dark-600))",
            700: "rgba(var(--custom-colors-orange-dark-700))",
            800: "rgba(var(--custom-colors-orange-dark-800))",
            900: "rgba(var(--custom-colors-orange-dark-900))",
          },
          orange: {
            50: "rgba(var(--custom-colors-orange-50))",
            100: "rgba(var(--custom-colors-orange-100))",
            200: "rgba(var(--custom-colors-orange-200))",
            300: "rgba(var(--custom-colors-orange-300))",
            400: "rgba(var(--custom-colors-orange-400))",
            500: "rgba(var(--custom-colors-orange-500))",
            600: "rgba(var(--custom-colors-orange-600))",
            700: "rgba(var(--custom-colors-orange-700))",
            800: "rgba(var(--custom-colors-orange-800))",
            900: "rgba(var(--custom-colors-orange-900))",
          },
          yellow: {
            50: "rgba(var(--custom-colors-yellow-50))",
            100: "rgba(var(--custom-colors-yellow-100))",
            200: "rgba(var(--custom-colors-yellow-200))",
            300: "rgba(var(--custom-colors-yellow-300))",
            400: "rgba(var(--custom-colors-yellow-400))",
            500: "rgba(var(--custom-colors-yellow-500))",
            600: "rgba(var(--custom-colors-yellow-600))",
            700: "rgba(var(--custom-colors-yellow-700))",
            800: "rgba(var(--custom-colors-yellow-800))",
            900: "rgba(var(--custom-colors-yellow-900))",
          },
          rose: {
            50: "rgba(var(--custom-colors-rose-50))",
            100: "rgba(var(--custom-colors-rose-100))",
            200: "rgba(var(--custom-colors-rose-200))",
            300: "rgba(var(--custom-colors-rose-300))",
            400: "rgba(var(--custom-colors-rose-400))",
            500: "rgba(var(--custom-colors-rose-500))",
            600: "rgba(var(--custom-colors-rose-600))",
            700: "rgba(var(--custom-colors-rose-700))",
            800: "rgba(var(--custom-colors-rose-800))",
            900: "rgba(var(--custom-colors-rose-900))",
          },
          teal: {
            50: "rgba(var(--custom-colors-teal-50))",
            100: "rgba(var(--custom-colors-teal-100))",
            200: "rgba(var(--custom-colors-teal-200))",
            300: "rgba(var(--custom-colors-teal-300))",
            400: "rgba(var(--custom-colors-teal-400))",
            500: "rgba(var(--custom-colors-teal-500))",
            600: "rgba(var(--custom-colors-teal-600))",
            700: "rgba(var(--custom-colors-teal-700))",
            800: "rgba(var(--custom-colors-teal-800))",
            900: "rgba(var(--custom-colors-teal-900))",
          },
          violet: {
            50: "rgba(var(--custom-colors-violet-50))",
            100: "rgba(var(--custom-colors-violet-100))",
            200: "rgba(var(--custom-colors-violet-200))",
            300: "rgba(var(--custom-colors-violet-300))",
            400: "rgba(var(--custom-colors-violet-400))",
            500: "rgba(var(--custom-colors-violet-500))",
            600: "rgba(var(--custom-colors-violet-600))",
            700: "rgba(var(--custom-colors-violet-700))",
            800: "rgba(var(--custom-colors-violet-800))",
            900: "rgba(var(--custom-colors-violet-900))",
          },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@headlessui/tailwindcss"),
    require("@tailwindcss/typography"),
  ],
};
