/**
 * Comprehensive mapping of common email domain typos to their correct versions
 * This includes the most frequently observed typos in real-world email inputs
 */
const EMAIL_TYPO_CORRECTIONS: Record<string, string> = {
  // Gmail typos
  "gmai.com": "gmail.com",
  "gmal.com": "gmail.com",
  "gmial.com": "gmail.com",
  "gmaail.com": "gmail.com",
  "gmall.com": "gmail.com",
  "gmali.com": "gmail.com",
  "gmaill.com": "gmail.com",
  "gamil.com": "gmail.com",
  "gamail.com": "gmail.com",
  "gmaul.com": "gmail.com",
  "gmaqil.com": "gmail.com",
  "gmaikl.com": "gmail.com",
  "gmailo.com": "gmail.com",
  "gmailn.com": "gmail.com",
  "gmailp.com": "gmail.com",
  "gmails.com": "gmail.com",
  "gmailt.com": "gmail.com",
  "fmail.com": "gmail.com",
  "gail.com": "gmail.com",
  "gmil.com": "gmail.com",
  "gmoil.com": "gmail.com",
  "gmuil.com": "gmail.com",
  "gymail.com": "gmail.com",
  "bmail.com": "gmail.com",
  "nmail.com": "gmail.com",
  "jmail.com": "gmail.com",
  "tmail.com": "gmail.com",
  "gmai;.com": "gmail.com",
  "gmaio.com": "gmail.com",
  "gmaiil.com": "gmail.com",
  "gmailm.com": "gmail.com",
  "gnail.com": "gmail.com",
  "gmsil.com": "gmail.com",
  "gmeil.com": "gmail.com",
  "gimail.com": "gmail.com",
  "gmaik.com": "gmail.com",
  "hmail.com": "gmail.com",
  "vmail.com": "gmail.com",
  "rmail.com": "gmail.com",
  "ymail.com": "gmail.com",
  "gmaol.com": "gmail.com",
  "gmayl.com": "gmail.com",
  "gmapl.com": "gmail.com",
  "gmail.com": "gmail.com",
  "gmasl.com": "gmail.com",
  "gmadl.com": "gmail.com",
  "gmafl.com": "gmail.com",
  "gmagl.com": "gmail.com",
  "gmabl.com": "gmail.com",
  "gmajl.com": "gmail.com",
  "gmakl.com": "gmail.com",
  "gmazl.com": "gmail.com",
  "gmahl.com": "gmail.com",
  "gmanl.com": "gmail.com",
  "gmarl.com": "gmail.com",
  "gmatl.com": "gmail.com",
  "gmaml.com": "gmail.com",
  "gmawl.com": "gmail.com",
  "gmaxl.com": "gmail.com",
  "gmavl.com": "gmail.com",
  "gmaqi.com": "gmail.com",
  "gmawi.com": "gmail.com",
  "gmaei.com": "gmail.com",
  "gmari.com": "gmail.com",
  "gmati.com": "gmail.com",
  "gmayi.com": "gmail.com",
  "gmaui.com": "gmail.com",
  "gmaoi.com": "gmail.com",
  "gmai.co": "gmail.com",
  "gmai.net": "gmail.com",
  "gmai.org": "gmail.com",
  "gmail.co": "gmail.com",
  "gmail.con": "gmail.com",
  "gmail.cm": "gmail.com",
  "gmail.om": "gmail.com",
  "gmail.coom": "gmail.com",
  "gmail.cim": "gmail.com",
  "gmail.xom": "gmail.com",
  "gmail.vom": "gmail.com",
  "gmail.fom": "gmail.com",
  "gmail.dom": "gmail.com",
  "gmail.som": "gmail.com",
  "gmail.c0m": "gmail.com",
  "gmail.c9m": "gmail.com",
  "gmail.coj": "gmail.com",
  "gmail.cok": "gmail.com",
  "gmail.col": "gmail.com",
  "gmail.cop": "gmail.com",
  "gmail.ocm": "gmail.com",

  // Yahoo typos
  "yaho.com": "yahoo.com",
  "yahoo.co": "yahoo.com",
  "yahho.com": "yahoo.com",
  "yahooo.com": "yahoo.com",
  "yahoo.cm": "yahoo.com",
  "yahoo.con": "yahoo.com",
  "yahoo.om": "yahoo.com",
  "yahol.com": "yahoo.com",
  "yajoo.com": "yahoo.com",
  "yaoo.com": "yahoo.com",
  "yhaoo.com": "yahoo.com",
  "yhoo.com": "yahoo.com",
  "yahoo.com": "yahoo.com",
  "yqhoo.com": "yahoo.com",
  "ywhoo.com": "yahoo.com",
  "yshoo.com": "yahoo.com",
  "yzhoo.com": "yahoo.com",
  "yahoop.com": "yahoo.com",
  "yahooi.com": "yahoo.com",
  "yahooe.com": "yahoo.com",
  "yahoou.com": "yahoo.com",
  "yahooy.com": "yahoo.com",
  "yahooh.com": "yahoo.com",
  "yahioo.com": "yahoo.com",
  "yahuoo.com": "yahoo.com",
  "yayhoo.com": "yahoo.com",
  "yahooa.com": "yahoo.com",
  "yahhoo.com": "yahoo.com",
  "yahoo.coom": "yahoo.com",
  "yahoo.cim": "yahoo.com",
  "yahoo.xom": "yahoo.com",
  "yahoo.vom": "yahoo.com",
  "yahoo.fom": "yahoo.com",
  "yahoo.dom": "yahoo.com",
  "yahoo.som": "yahoo.com",
  "yahoo.c0m": "yahoo.com",
  "yahoo.c9m": "yahoo.com",
  "yahoo.coj": "yahoo.com",
  "yahoo.cok": "yahoo.com",
  "yahoo.col": "yahoo.com",
  "yahoo.cop": "yahoo.com",
  "yahoo.co,": "yahoo.com",
  "yahoo.co.": "yahoo.com",
  "yahoo.ocm": "yahoo.com",

  // Hotmail typos
  "hotmai.com": "hotmail.com",
  "hotmial.com": "hotmail.com",
  "hotamil.com": "hotmail.com",
  "hotmaill.com": "hotmail.com",
  "hotmail.co": "hotmail.com",
  "hotmail.con": "hotmail.com",
  "hotmail.cm": "hotmail.com",
  "hotmail.om": "hotmail.com",
  "hotmil.com": "hotmail.com",
  "hotmall.com": "hotmail.com",
  "htomail.com": "hotmail.com",
  "hotmal.com": "hotmail.com",
  "hatmail.com": "hotmail.com",
  "hitmail.com": "hotmail.com",
  "hutmail.com": "hotmail.com",
  "hetmail.com": "hotmail.com",
  "hotmqil.com": "hotmail.com",
  "hotmwil.com": "hotmail.com",
  "hotmsil.com": "hotmail.com",
  "hotmzil.com": "hotmail.com",
  "hotmaip.com": "hotmail.com",
  "hotmaio.com": "hotmail.com",
  "hotmaik.com": "hotmail.com",
  "hotmaim.com": "hotmail.com",
  "hotmaiil.com": "hotmail.com",
  "hotmaail.com": "hotmail.com",
  "hotmaiyl.com": "hotmail.com",
  "hotmaihl.com": "hotmail.com",
  "hotmaigl.com": "hotmail.com",
  "hotmaifl.com": "hotmail.com",
  "hotmaidl.com": "hotmail.com",
  "hotmaisl.com": "hotmail.com",
  "hotmaijl.com": "hotmail.com",
  "hotmeil.com": "hotmail.com",
  "hotmaul.com": "hotmail.com",
  "hotmali.com": "hotmail.com",
  "hoymail.com": "hotmail.com",
  "hotmai;.com": "hotmail.com",
  "hotmail.coom": "hotmail.com",
  "hotmail.cim": "hotmail.com",
  "hotmail.xom": "hotmail.com",
  "hotmail.vom": "hotmail.com",
  "hotmail.fom": "hotmail.com",
  "hotmail.dom": "hotmail.com",
  "hotmail.som": "hotmail.com",
  "hotmail.c0m": "hotmail.com",
  "hotmail.c9m": "hotmail.com",
  "hotmail.coj": "hotmail.com",
  "hotmail.cok": "hotmail.com",
  "hotmail.col": "hotmail.com",
  "hotmail.cop": "hotmail.com",
  "hotmail.co,": "hotmail.com",
  "hotmail.co.": "hotmail.com",
  "hotmail.ocm": "hotmail.com",

  // Outlook typos
  "outlok.com": "outlook.com",
  "outlook.co": "outlook.com",
  "outlokk.com": "outlook.com",
  "outlook.con": "outlook.com",
  "outlook.cm": "outlook.com",
  "outlook.om": "outlook.com",
  "outloook.com": "outlook.com",
  "outlool.com": "outlook.com",
  "outluke.com": "outlook.com",
  "oultook.com": "outlook.com",
  "outlokc.com": "outlook.com",
  "outlhook.com": "outlook.com",
  "outloo.com": "outlook.com",
  "outllok.com": "outlook.com",
  "outlouk.com": "outlook.com",
  "outtlook.com": "outlook.com",
  "outluk.com": "outlook.com",
  "outlik.com": "outlook.com",
  "outlookk.com": "outlook.com",
  "outllook.com": "outlook.com",
  "outlkook.com": "outlook.com",
  "outlpok.com": "outlook.com",
  "outliok.com": "outlook.com",
  "outlolok.com": "outlook.com",
  "outlopk.com": "outlook.com",
  "outlmook.com": "outlook.com",
  "outlnook.com": "outlook.com",
  "outlookm.com": "outlook.com",
  "outlookn.com": "outlook.com",
  "outlookp.com": "outlook.com",
  "outlooki.com": "outlook.com",
  "outlooko.com": "outlook.com",
  "outlooku.com": "outlook.com",
  "outlooke.com": "outlook.com",
  "outlook.coom": "outlook.com",
  "outlook.cim": "outlook.com",
  "outlook.xom": "outlook.com",
  "outlook.vom": "outlook.com",
  "outlook.fom": "outlook.com",
  "outlook.dom": "outlook.com",
  "outlook.som": "outlook.com",
  "outlook.c0m": "outlook.com",
  "outlook.c9m": "outlook.com",
  "outlook.coj": "outlook.com",
  "outlook.cok": "outlook.com",
  "outlook.col": "outlook.com",
  "outlook.cop": "outlook.com",
  "outlook.co,": "outlook.com",
  "outlook.co.": "outlook.com",
  "outlook.ocm": "outlook.com",

  // iCloud typos
  "iclou.com": "icloud.com",
  "icloud.co": "icloud.com",
  "iclud.com": "icloud.com",
  "iclound.com": "icloud.com",
  "icloud.con": "icloud.com",
  "icloud.cm": "icloud.com",
  "icloud.om": "icloud.com",
  "icloid.com": "icloud.com",
  "iclodu.com": "icloud.com",
  "iclowd.com": "icloud.com",
  "iclou d.com": "icloud.com",
  "icoud.com": "icloud.com",
  "iclod.com": "icloud.com",
  "icluod.com": "icloud.com",
  "icolud.com": "icloud.com",
  "iclorud.com": "icloud.com",
  "iclournd.com": "icloud.com",
  "iclouyd.com": "icloud.com",
  "icloyud.com": "icloud.com",
  "iclouhd.com": "icloud.com",
  "icloujd.com": "icloud.com",
  "iclougd.com": "icloud.com",
  "icloufd.com": "icloud.com",
  "icloudd.com": "icloud.com",
  "iclousd.com": "icloud.com",
  "icloubd.com": "icloud.com",
  "icloudm.com": "icloud.com",
  "icloudn.com": "icloud.com",
  "icloudp.com": "icloud.com",
  "icloudi.com": "icloud.com",
  "icloudo.com": "icloud.com",
  "icloudu.com": "icloud.com",
  "icloude.com": "icloud.com",
  "icloud.coom": "icloud.com",
  "icloud.cim": "icloud.com",
  "icloud.xom": "icloud.com",
  "icloud.vom": "icloud.com",
  "icloud.fom": "icloud.com",
  "icloud.dom": "icloud.com",
  "icloud.som": "icloud.com",
  "icloud.c0m": "icloud.com",
  "icloud.c9m": "icloud.com",
  "icloud.coj": "icloud.com",
  "icloud.cok": "icloud.com",
  "icloud.col": "icloud.com",
  "icloud.cop": "icloud.com",
  "icloud.co,": "icloud.com",
  "icloud.co.": "icloud.com",
  "icloud.ocm": "icloud.com",

  // AOL typos
  "aol.co": "aol.com",
  "aol.con": "aol.com",
  "aol.cm": "aol.com",
  "aol.om": "aol.com",
  "aol.coom": "aol.com",
  "aol.cim": "aol.com",
  "aol.xom": "aol.com",
  "aol.vom": "aol.com",
  "aol.fom": "aol.com",
  "aol.dom": "aol.com",
  "aol.som": "aol.com",
  "aol.c0m": "aol.com",
  "aol.c9m": "aol.com",
  "aol.coj": "aol.com",
  "aol.cok": "aol.com",
  "aol.col": "aol.com",
  "aol.cop": "aol.com",
  "aol.co,": "aol.com",
  "aol.co.": "aol.com",
  "aol.ocm": "aol.com",

  // Live typos
  "live.co": "live.com",
  "live.con": "live.com",
  "live.cm": "live.com",
  "live.om": "live.com",
  "live.coom": "live.com",
  "live.cim": "live.com",
  "live.xom": "live.com",
  "live.vom": "live.com",
  "live.fom": "live.com",
  "live.dom": "live.com",
  "live.som": "live.com",
  "live.c0m": "live.com",
  "live.c9m": "live.com",
  "live.coj": "live.com",
  "live.cok": "live.com",
  "live.col": "live.com",
  "live.cop": "live.com",
  "live.co,": "live.com",
  "live.co.": "live.com",
  "live.ocm": "live.com",

  // MSN typos
  "msn.co": "msn.com",
  "msn.con": "msn.com",
  "msn.cm": "msn.com",
  "msn.om": "msn.com",
  "msn.coom": "msn.com",
  "msn.cim": "msn.com",
  "msn.xom": "msn.com",
  "msn.vom": "msn.com",
  "msn.fom": "msn.com",
  "msn.dom": "msn.com",
  "msn.som": "msn.com",
  "msn.c0m": "msn.com",
  "msn.c9m": "msn.com",
  "msn.coj": "msn.com",
  "msn.cok": "msn.com",
  "msn.col": "msn.com",
  "msn.cop": "msn.com",
  "msn.co,": "msn.com",
  "msn.co.": "msn.com",
  "msn.ocm": "msn.com",

  // Me.com typos
  "me.co": "me.com",
  "me.con": "me.com",
  "me.cm": "me.com",
  "me.om": "me.com",
  "me.coom": "me.com",
  "me.cim": "me.com",
  "me.xom": "me.com",
  "me.vom": "me.com",
  "me.fom": "me.com",
  "me.dom": "me.com",
  "me.som": "me.com",
  "me.c0m": "me.com",
  "me.c9m": "me.com",
  "me.coj": "me.com",
  "me.cok": "me.com",
  "me.col": "me.com",
  "me.cop": "me.com",
  "me.co,": "me.com",
  "me.co.": "me.com",
  "me.ocm": "me.com",

  // Mac.com typos
  "mac.co": "mac.com",
  "mac.con": "mac.com",
  "mac.cm": "mac.com",
  "mac.om": "mac.com",
  "mac.coom": "mac.com",
  "mac.cim": "mac.com",
  "mac.xom": "mac.com",
  "mac.vom": "mac.com",
  "mac.fom": "mac.com",
  "mac.dom": "mac.com",
  "mac.som": "mac.com",
  "mac.c0m": "mac.com",
  "mac.c9m": "mac.com",
  "mac.coj": "mac.com",
  "mac.cok": "mac.com",
  "mac.col": "mac.com",
  "mac.cop": "mac.com",
  "mac.co,": "mac.com",
  "mac.co.": "mac.com",
  "mac.ocm": "mac.com",

  // ProtonMail typos
  "protonmail.co": "protonmail.com",
  "protonmail.con": "protonmail.com",
  "protonmail.cm": "protonmail.com",
  "protonmail.om": "protonmail.com",
  "protonmal.com": "protonmail.com",
  "protonmaill.com": "protonmail.com",
  "protonmail.coom": "protonmail.com",
  "protonmail.cim": "protonmail.com",
  "protonmail.xom": "protonmail.com",
  "protonmail.vom": "protonmail.com",
  "protonmail.fom": "protonmail.com",
  "protonmail.dom": "protonmail.com",
  "protonmail.som": "protonmail.com",
  "protonmail.c0m": "protonmail.com",
  "protonmail.c9m": "protonmail.com",
  "protonmail.coj": "protonmail.com",
  "protonmail.cok": "protonmail.com",
  "protonmail.col": "protonmail.com",
  "protonmail.cop": "protonmail.com",
  "protonmail.co,": "protonmail.com",
  "protonmail.co.": "protonmail.com",
  "protonmail.ocm": "protonmail.com",

  // Ymail typos
  "ymail.co": "ymail.com",
  "ymail.con": "ymail.com",
  "ymail.cm": "ymail.com",
  "ymail.om": "ymail.com",
  "ymail.coom": "ymail.com",
  "ymail.cim": "ymail.com",
  "ymail.xom": "ymail.com",
  "ymail.vom": "ymail.com",
  "ymail.fom": "ymail.com",
  "ymail.dom": "ymail.com",
  "ymail.som": "ymail.com",
  "ymail.c0m": "ymail.com",
  "ymail.c9m": "ymail.com",
  "ymail.coj": "ymail.com",
  "ymail.cok": "ymail.com",
  "ymail.col": "ymail.com",
  "ymail.cop": "ymail.com",
  "ymail.co,": "ymail.com",
  "ymail.co.": "ymail.com",
  "ymail.ocm": "ymail.com",
};

/**
 * Checks an email address for common domain typos and suggests corrections
 * @param email - The email address to check
 * @returns The corrected email address, or the original if no correction is needed
 */
export function checkEmail(email: string): string {
  if (!email || typeof email !== "string") {
    return email;
  }

  // Split email into local and domain parts (email is pre-validated)
  const emailParts = email.toLowerCase().trim().split("@");
  const [localPart, domain] = emailParts;
  if (!domain) {
    return "";
  }

  // Check if the domain has a known typo correction
  const correctedDomain = EMAIL_TYPO_CORRECTIONS[domain];
  if (correctedDomain) {
    return `${localPart}@${correctedDomain}`;
  }

  // No correction needed
  return "";
}
