import { IConstant } from "../types/constants";

export const states: IConstant[] = [
  { id: "al", label: "Alabama", aliases: ["al"] },
  { id: "ak", label: "Alaska", aliases: ["ak"] },
  { id: "az", label: "Arizona", aliases: ["az"] },
  { id: "ar", label: "Arkansas", aliases: ["ar"] },
  { id: "ca", label: "California", aliases: ["ca"] },
  { id: "co", label: "Colorado", aliases: ["co"] },
  { id: "ct", label: "Connecticut", aliases: ["ct"] },
  { id: "de", label: "Delaware", aliases: ["de"] },
  {
    id: "dc",
    label: "District Of Columbia",
    aliases: ["dc", "washington d.c.", "washington dc"],
  },
  { id: "fl", label: "Florida", aliases: ["fl"] },
  { id: "ga", label: "Georgia", aliases: ["ga"] },
  { id: "hi", label: "Hawaii", aliases: ["hi"] },
  { id: "id", label: "Idaho", aliases: ["id"] },
  { id: "il", label: "Illinois", aliases: ["il"] },
  { id: "in", label: "Indiana", aliases: ["in"] },
  { id: "ia", label: "Iowa", aliases: ["ia"] },
  { id: "ks", label: "Kansas", aliases: ["ks"] },
  { id: "ky", label: "Kentucky", aliases: ["ky"] },
  { id: "la", label: "Louisiana", aliases: ["la"] },
  { id: "me", label: "Maine", aliases: ["me"] },
  { id: "md", label: "Maryland", aliases: ["md"] },
  { id: "ma", label: "Massachusetts", aliases: ["ma"] },
  { id: "mi", label: "Michigan", aliases: ["mi"] },
  { id: "mn", label: "Minnesota", aliases: ["mn"] },
  { id: "ms", label: "Mississippi", aliases: ["ms"] },
  { id: "mo", label: "Missouri", aliases: ["mo"] },
  { id: "mt", label: "Montana", aliases: ["mt"] },
  { id: "ne", label: "Nebraska", aliases: ["ne"] },
  { id: "nv", label: "Nevada", aliases: ["nv"] },
  { id: "nh", label: "New Hampshire", aliases: ["nh"] },
  { id: "nj", label: "New Jersey", aliases: ["nj"] },
  { id: "nm", label: "New Mexico", aliases: ["nm"] },
  { id: "ny", label: "New York", aliases: ["ny"] },
  { id: "nc", label: "North Carolina", aliases: ["nc"] },
  { id: "nd", label: "North Dakota", aliases: ["nd"] },
  { id: "oh", label: "Ohio", aliases: ["oh"] },
  { id: "ok", label: "Oklahoma", aliases: ["ok"] },
  { id: "or", label: "Oregon", aliases: ["or"] },
  { id: "pa", label: "Pennsylvania", aliases: ["pa"] },
  { id: "ri", label: "Rhode Island", aliases: ["ri"] },
  { id: "sc", label: "South Carolina", aliases: ["sc"] },
  { id: "sd", label: "South Dakota", aliases: ["sd"] },
  { id: "tn", label: "Tennessee", aliases: ["tn"] },
  { id: "tx", label: "Texas", aliases: ["tx"] },
  { id: "ut", label: "Utah", aliases: ["ut"] },
  { id: "vt", label: "Vermont", aliases: ["vt"] },
  { id: "va", label: "Virginia", aliases: ["va"] },
  { id: "wa", label: "Washington", aliases: ["wa"] },
  { id: "wv", label: "West Virginia", aliases: ["wv"] },
  { id: "wi", label: "Wisconsin", aliases: ["wi"] },
  { id: "wy", label: "Wyoming", aliases: ["wy"] },
];
