// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * AccountGEN_Account
 */
export type AccountGenAccount = {
    created_at: string;
    created_by_urn: string;
    deleted: number;
    disabled: number;
    email: string;
    email_verified_at_ts: number;
    external_id: string;
    external_user_info?: unknown;
    first_name: string;
    hashed_password: string;
    id: string;
    invite_key?: string;
    invite_ts?: number;
    is_oauth: number;
    is_super_user_session: number;
    last_login_ts: number;
    last_name: string;
    last_seen?: number;
    organization_id: string;
    password_updated_at_ts: number;
    phone: string;
    role: number;
    status: number;
    test_user_type: number;
    updated_at: string;
    updated_by_urn: string;
    urn: string;
    verify_email_key?: string;
};

/**
 * AccountGEN_AccountJoined
 */
export type AccountGenAccountJoined = {
    created_at: string;
    created_by_name: string;
    created_by_urn: string;
    deleted: number;
    disabled: number;
    email: string;
    email_verified_at_ts: number;
    external_id: string;
    external_user_info?: unknown;
    first_name: string;
    hashed_password: string;
    id: string;
    invite_key?: string;
    invite_ts?: number;
    is_oauth: number;
    is_super_user_session: number;
    last_login_ts: number;
    last_name: string;
    last_seen?: number;
    name: string;
    organization_id: string;
    password_updated_at_ts: number;
    phone: string;
    role: number;
    status: number;
    test_user_type: number;
    updated_at: string;
    updated_by_name: string;
    updated_by_urn: string;
    urn: string;
    verify_email_key?: string;
};

/**
 * AccountGEN_AccountJoinedPublic
 */
export type AccountGenAccountJoinedPublic = {
    [key: string]: unknown;
};

/**
 * AccountGEN_AccountPublic
 */
export type AccountGenAccountPublic = {
    [key: string]: unknown;
};

/**
 * AccountGEN_AccountWithFeatures
 */
export type AccountGenAccountWithFeatures = {
    billing_plan_level: number;
    billing_plan_price: number;
    created_at: string;
    created_by_name: string;
    created_by_urn: string;
    deleted: number;
    disabled: number;
    email: string;
    email_verified_at_ts: number;
    external_id: string;
    external_user_info?: unknown;
    first_name: string;
    hashed_password: string;
    id: string;
    invite_key?: string;
    invite_ts?: number;
    is_oauth: number;
    is_super_user_session: number;
    last_login_ts: number;
    last_name: string;
    last_seen?: number;
    list_assets: number;
    name: string;
    organization_id: string;
    password_updated_at_ts: number;
    phone: string;
    role: number;
    status: number;
    test_user_type: number;
    updated_at: string;
    updated_by_name: string;
    updated_by_urn: string;
    urn: string;
    verify_email_key?: string;
};

/**
 * AccountGEN_AccountWithFeaturesPublic
 */
export type AccountGenAccountWithFeaturesPublic = {
    list_assets: number;
};

/**
 * AuthGetMethodsResponse
 */
export type AuthGetMethodsResponse = {
    methods: Array<AuthenticationMethodAuthenticationType>;
    not_setup: boolean;
};

/**
 * AuthGetMethodsResponsePublic
 */
export type AuthGetMethodsResponsePublic = {
    [key: string]: unknown;
};

/**
 * AuthInitiateRegisterResponse
 */
export type AuthInitiateRegisterResponse = {
    auth_challenge: AuthServiceAuthChallenge;
};

/**
 * AuthInitiateRegisterResponsePublic
 */
export type AuthInitiateRegisterResponsePublic = {
    [key: string]: unknown;
};

/**
 * AuthInitiateTwoFARequest
 */
export type AuthInitiateTwoFaRequest = {
    authentication_method_id: string;
};

/**
 * AuthInitiateTwoFARequestPublic
 */
export type AuthInitiateTwoFaRequestPublic = {
    [key: string]: unknown;
};

/**
 * AuthMethodsInput
 */
export type AuthMethodsInput = {
    identifier: string;
};

/**
 * AuthMethodsInputPublic
 */
export type AuthMethodsInputPublic = {
    [key: string]: unknown;
};

/**
 * AuthPasswordPostData
 */
export type AuthPasswordPostData = {
    password: string;
    password_confirmation: string;
};

/**
 * AuthPasswordPostDataPublic
 */
export type AuthPasswordPostDataPublic = {
    [key: string]: unknown;
};

/**
 * AuthVerifyResponse
 */
export type AuthVerifyResponse = {
    account_id?: string;
    required_2fa?: AuthenticationMethodAuthenticationType;
    session_token?: string;
    verified: boolean;
};

/**
 * AuthVerifyResponsePublic
 */
export type AuthVerifyResponsePublic = {
    [key: string]: unknown;
};

/**
 * AuthServiceAuthChallenge
 */
export type AuthServiceAuthChallenge = {
    account_auth_2fa_id?: string;
    account_auth_id: string;
    challenge_data?: AuthServiceChallengeData;
    challenge_id: string;
    expires_at: number;
    masked_identifier?: string;
    required_2fa?: AuthenticationMethodAuthenticationType;
    signup?: boolean;
    test_code?: string;
    two_fa_identifier?: string;
    type: AuthenticationMethodAuthenticationType;
    verified: boolean;
};

/**
 * AuthServiceAuthChallengePublic
 */
export type AuthServiceAuthChallengePublic = {
    [key: string]: unknown;
};

/**
 * AuthServiceChallengeData
 */
export type AuthServiceChallengeData = {
    challenge?: string;
    code_hash?: string;
    cred_params?: Array<ProtocolCredentialParameter>;
    email?: string;
    phone?: string;
    public_key_creation?: ProtocolPublicKeyCredentialCreationOptions;
    public_key_options?: ProtocolCredentialAssertion;
    user_urn?: TypesUrn;
    user_verification?: string;
    webauthn_user_id?: string;
};

/**
 * AuthServiceChallengeDataPublic
 */
export type AuthServiceChallengeDataPublic = {
    [key: string]: unknown;
};

/**
 * AuthServiceInitiateAuthParams
 */
export type AuthServiceInitiateAuthParams = {
    account_id?: string;
    identifier: string;
    oauth_provider?: AuthenticationMethodProvider;
    password?: string;
    remember_me?: boolean;
    token?: string;
    type: AuthenticationMethodAuthenticationType;
    user_verification?: string;
};

/**
 * AuthServiceInitiateAuthParamsPublic
 */
export type AuthServiceInitiateAuthParamsPublic = {
    [key: string]: unknown;
};

/**
 * AuthServiceVerifyAuthParams
 */
export type AuthServiceVerifyAuthParams = {
    authenticator_data?: string;
    challenge_id: string;
    client_data_json?: string;
    code?: string;
    credential_id?: string;
    remember_me?: boolean;
    response?: ProtocolCredentialCreationResponse;
    signature?: string;
    type: AuthenticationMethodAuthenticationType;
    user_handle?: string;
};

/**
 * AuthServiceVerifyAuthParamsPublic
 */
export type AuthServiceVerifyAuthParamsPublic = {
    [key: string]: unknown;
};

/**
 * AuthenticationMethod
 */
export type AuthenticationMethod = {
    challenge_value: string;
    created_at: string;
    created_by_urn: string;
    deleted: number;
    disabled: number;
    id: string;
    last_used_at_ts: number;
    provider: AuthenticationMethodProvider;
    session_keys: {
        [key: string]: AuthenticationMethodSessionKey;
    };
    settings: AuthenticationMethodSettings;
    status: ConstantsStatus;
    target: string;
    type: AuthenticationMethodAuthenticationType;
    updated_at: string;
    updated_by_urn: string;
    urn: string;
    user_urn: string;
    verified_at_ts: number;
};

/**
 * AuthenticationMethodPublic
 */
export type AuthenticationMethodPublic = {
    created_at: string;
    created_by_urn: string;
    deleted: number;
    disabled: number;
    id: string;
    provider: AuthenticationMethodProvider;
    session_keys: {
        [key: string]: AuthenticationMethodSessionKeyPublic;
    };
    settings: AuthenticationMethodSettingsPublic;
    status: ConstantsStatus;
    target: string;
    type: AuthenticationMethodAuthenticationType;
    updated_at: string;
    updated_by_urn: string;
    urn: string;
};

/**
 * AuthenticationMethodAuthenticationType
 */
export enum AuthenticationMethodAuthenticationType {
    /**
     * AUTHENTICATION_TYPE_PASSWORD
     */
    AUTHENTICATION_TYPE_PASSWORD = 1,
    /**
     * AUTHENTICATION_TYPE_EMAIL_OTP
     */
    AUTHENTICATION_TYPE_EMAIL_OTP = 2,
    /**
     * AUTHENTICATION_TYPE_SMS_OTP
     */
    AUTHENTICATION_TYPE_SMS_OTP = 3,
    /**
     * AUTHENTICATION_TYPE_PASSKEY
     */
    AUTHENTICATION_TYPE_PASSKEY = 4,
    /**
     * AUTHENTICATION_TYPE_2FA_KEY
     */
    AUTHENTICATION_TYPE_2FA_KEY = 5,
    /**
     * AUTHENTICATION_TYPE_2FA_PHONE
     */
    AUTHENTICATION_TYPE_2FA_PHONE = 6,
    /**
     * AUTHENTICATION_TYPE_2FA_EMAIL
     */
    AUTHENTICATION_TYPE_2FA_EMAIL = 7,
    /**
     * AUTHENTICATION_TYPE_OAUTH
     */
    AUTHENTICATION_TYPE_OAUTH = 8,
    /**
     * AUTHENTICATION_TYPE_MAGIC_LINK
     */
    AUTHENTICATION_TYPE_MAGIC_LINK = 9
}

/**
 * AuthenticationMethodProvider
 */
export enum AuthenticationMethodProvider {
    /**
     * PROVIDER_OAUTH_NJEA
     */
    PROVIDER_OAUTH_NJEA = 'njea',
    /**
     * PROVIDER_OAUTH_GOOGLE
     */
    PROVIDER_OAUTH_GOOGLE = 'google'
}

/**
 * AuthenticationMethodSessionKey
 */
export type AuthenticationMethodSessionKey = {
    city: string;
    continent: string;
    country: string;
    created_at: number;
    expires_at: number;
    ip_address: string;
    latitude: string;
    longitude: string;
    metro_code: string;
    postal_code: string;
    region: string;
    region_code: string;
    session_key: string;
    timezone: string;
    user_agent: string;
};

/**
 * AuthenticationMethodSessionKeyPublic
 */
export type AuthenticationMethodSessionKeyPublic = {
    [key: string]: unknown;
};

/**
 * AuthenticationMethodSettings
 */
export type AuthenticationMethodSettings = {
    aaguid: string;
    backup_eligible: boolean;
    backup_state: boolean;
    device_name: string;
    platform: string;
    sign_count: number;
    transports: Array<ProtocolAuthenticatorTransport>;
    user_present: boolean;
    user_verified: boolean;
};

/**
 * AuthenticationMethodSettingsPublic
 */
export type AuthenticationMethodSettingsPublic = {
    device_name: string;
    platform: string;
};

/**
 * ConstantsStatus
 */
export enum ConstantsStatus {
    /**
     * STATUS_ACTIVE
     *
     * Active
     */
    STATUS_ACTIVE = 100,
    /**
     * STATUS_DISABLED
     *
     * Disabled
     */
    STATUS_DISABLED = 200,
    /**
     * STATUS_DELETED
     *
     * Deleted
     */
    STATUS_DELETED = 300
}

/**
 * ResponseErrorResponse
 */
export type GithubComGriffnbCoreLibRouterResponseErrorResponse = {
    data?: unknown;
    error: string;
    success: boolean;
};

/**
 * ResponseErrorResponsePublic
 */
export type GithubComGriffnbCoreLibRouterResponseErrorResponsePublic = {
    [key: string]: unknown;
};

/**
 * ResponseSuccessResponse
 */
export type GithubComGriffnbCoreLibRouterResponseSuccessResponse = {
    data: unknown;
    error?: string;
    success: boolean;
};

/**
 * ResponseSuccessResponsePublic
 */
export type GithubComGriffnbCoreLibRouterResponseSuccessResponsePublic = {
    [key: string]: unknown;
};

/**
 * ProtocolAttestationFormat
 */
export enum ProtocolAttestationFormat {
    /**
     * AttestationFormatPacked
     *
     * authenticators with limited resources (e.g., secure elements).
     */
    ATTESTATION_FORMAT_PACKED = 'packed',
    /**
     * AttestationFormatTPM
     *
     * as the packed attestation statement format, although the rawData and signature fields are computed differently.
     */
    ATTESTATION_FORMAT_TPM = 'tpm',
    /**
     * AttestationFormatAndroidKey
     *
     * later, which may provide this proprietary "hardware attestation" statement.
     */
    ATTESTATION_FORMAT_ANDROID_KEY = 'android-key',
    /**
     * AttestationFormatAndroidSafetyNet
     *
     * MAY produce an attestation statement based on the Android SafetyNet API.
     */
    ATTESTATION_FORMAT_ANDROID_SAFETY_NET = 'android-safetynet',
    /**
     * AttestationFormatFIDOUniversalSecondFactor
     *
     * authenticators.
     */
    ATTESTATION_FORMAT_FIDO_UNIVERSAL_SECOND_FACTOR = 'fido-u2f',
    /**
     * AttestationFormatApple
     *
     * authenticators.
     */
    ATTESTATION_FORMAT_APPLE = 'apple',
    /**
     * AttestationFormatCompound
     *
     * AttestationFormatCompound is used to pass multiple, self-contained attestation statements in a single ceremony.
     */
    ATTESTATION_FORMAT_COMPOUND = 'compound',
    /**
     * AttestationFormatNone
     *
     * attestation statement when a WebAuthn Relying Party indicates it does not wish to receive attestation information.
     */
    ATTESTATION_FORMAT_NONE = 'none'
}

/**
 * ProtocolAuthenticationExtensions
 */
export type ProtocolAuthenticationExtensions = {
    [key: string]: unknown;
};

/**
 * ProtocolAuthenticationExtensionsClientOutputs
 */
export type ProtocolAuthenticationExtensionsClientOutputs = {
    [key: string]: unknown;
};

/**
 * ProtocolAuthenticatorAttachment
 */
export enum ProtocolAuthenticatorAttachment {
    /**
     * Platform
     *
     * platform authenticator is called a platform credential.
     */
    PLATFORM = 'platform',
    /**
     * CrossPlatform
     *
     * A public key credential bound to a roaming authenticator is called a roaming credential.
     */
    CROSS_PLATFORM = 'cross-platform'
}

/**
 * ProtocolAuthenticatorTransport
 */
export enum ProtocolAuthenticatorTransport {
    /**
     * USB
     *
     * USB indicates the respective authenticator can be contacted over removable USB.
     */
    USB = 'usb',
    /**
     * NFC
     *
     * NFC indicates the respective authenticator can be contacted over Near Field Communication (NFC).
     */
    NFC = 'nfc',
    /**
     * BLE
     *
     * BLE indicates the respective authenticator can be contacted over Bluetooth Smart (Bluetooth Low Energy / BLE).
     */
    BLE = 'ble',
    /**
     * SmartCard
     *
     * WebAuthn Level 3.
     */
    SMART_CARD = 'smart-card',
    /**
     * Hybrid
     *
     * WebAuthn Level 3.
     */
    HYBRID = 'hybrid',
    /**
     * Internal
     *
     * is a platform authenticator. These authenticators are not removable from the client device.
     */
    INTERNAL = 'internal'
}

/**
 * ProtocolConveyancePreference
 */
export enum ProtocolConveyancePreference {
    /**
     * PreferNoAttestation
     *
     * Specification: §5.4.7. Attestation Conveyance Preference Enumeration (https://www.w3.org/TR/webauthn/#dom-attestationconveyancepreference-none)
     */
    PREFER_NO_ATTESTATION = 'none',
    /**
     * PreferIndirectAttestation
     *
     * Specification: §5.4.7. Attestation Conveyance Preference Enumeration (https://www.w3.org/TR/webauthn/#dom-attestationconveyancepreference-indirect)
     */
    PREFER_INDIRECT_ATTESTATION = 'indirect',
    /**
     * PreferDirectAttestation
     *
     * Specification: §5.4.7. Attestation Conveyance Preference Enumeration (https://www.w3.org/TR/webauthn/#dom-attestationconveyancepreference-direct)
     */
    PREFER_DIRECT_ATTESTATION = 'direct',
    /**
     * PreferEnterpriseAttestation
     *
     * Specification: §5.4.7. Attestation Conveyance Preference Enumeration (https://www.w3.org/TR/webauthn/#dom-attestationconveyancepreference-enterprise)
     */
    PREFER_ENTERPRISE_ATTESTATION = 'enterprise'
}

/**
 * ProtocolCredentialAssertion
 */
export type ProtocolCredentialAssertion = {
    allowCredentials?: Array<ProtocolCredentialDescriptor>;
    challenge: ProtocolUrlEncodedBase64;
    extensions?: ProtocolAuthenticationExtensions;
    hints?: Array<ProtocolPublicKeyCredentialHints>;
    mediation?: ProtocolCredentialMediationRequirement;
    rpId?: string;
    timeout?: number;
    userVerification?: ProtocolUserVerificationRequirement;
};

/**
 * ProtocolCredentialAssertionPublic
 */
export type ProtocolCredentialAssertionPublic = {
    [key: string]: unknown;
};

/**
 * ProtocolCredentialCreationResponse
 */
export type ProtocolCredentialCreationResponse = {
    attestationObject: ProtocolUrlEncodedBase64;
    authenticatorAttachment?: string;
    authenticatorData: ProtocolUrlEncodedBase64;
    clientDataJSON: ProtocolUrlEncodedBase64;
    clientExtensionResults?: ProtocolAuthenticationExtensionsClientOutputs;
    id: string;
    publicKey: ProtocolUrlEncodedBase64;
    publicKeyAlgorithm: number;
    rawId: ProtocolUrlEncodedBase64;
    transports?: Array<string>;
    type: string;
};

/**
 * ProtocolCredentialCreationResponsePublic
 */
export type ProtocolCredentialCreationResponsePublic = {
    [key: string]: unknown;
};

/**
 * ProtocolCredentialDescriptor
 */
export type ProtocolCredentialDescriptor = {
    id: ProtocolUrlEncodedBase64;
    transports?: Array<ProtocolAuthenticatorTransport>;
    type: ProtocolCredentialType;
};

/**
 * ProtocolCredentialDescriptorPublic
 */
export type ProtocolCredentialDescriptorPublic = {
    [key: string]: unknown;
};

/**
 * ProtocolCredentialMediationRequirement
 */
export enum ProtocolCredentialMediationRequirement {
    /**
     * MediationDefault
     *
     * MediationDefault lets the browser choose the mediation flow completely as if it wasn't specified at all.
     */
    MEDIATION_DEFAULT = '',
    /**
     * MediationSilent
     *
     * than involving the user.
     */
    MEDIATION_SILENT = 'silent',
    /**
     * MediationOptional
     *
     * will be. If user mediation is required, then the user agent will involve the user in the decision.
     */
    MEDIATION_OPTIONAL = 'optional',
    /**
     * MediationConditional
     *
     * the conditional behavior always involves user mediation of some sort if applicable credentials are discovered.
     */
    MEDIATION_CONDITIONAL = 'conditional',
    /**
     * MediationRequired
     *
     * prevent silent access flag is unset for an origin.
     */
    MEDIATION_REQUIRED = 'required'
}

/**
 * ProtocolCredentialParameter
 */
export type ProtocolCredentialParameter = {
    alg: WebauthncoseCoseAlgorithmIdentifier;
    type: ProtocolCredentialType;
};

/**
 * ProtocolCredentialParameterPublic
 */
export type ProtocolCredentialParameterPublic = {
    [key: string]: unknown;
};

/**
 * ProtocolCredentialType
 */
export enum ProtocolCredentialType {
    /**
     * PublicKeyCredentialType
     *
     * PublicKeyCredentialType - Currently one credential type is defined, namely "public-key".
     */
    PUBLIC_KEY_CREDENTIAL_TYPE = 'public-key'
}

/**
 * ProtocolPublicKeyCredentialCreationOptions
 */
export type ProtocolPublicKeyCredentialCreationOptions = {
    attestation?: ProtocolConveyancePreference;
    attestationFormats?: Array<ProtocolAttestationFormat>;
    authenticatorAttachment?: ProtocolAuthenticatorAttachment;
    challenge: ProtocolUrlEncodedBase64;
    displayName: string;
    excludeCredentials?: Array<ProtocolCredentialDescriptor>;
    extensions?: ProtocolAuthenticationExtensions;
    hints?: Array<ProtocolPublicKeyCredentialHints>;
    id: unknown;
    name: string;
    pubKeyCredParams?: Array<ProtocolCredentialParameter>;
    requireResidentKey?: boolean;
    residentKey?: ProtocolResidentKeyRequirement;
    timeout?: number;
    userVerification?: ProtocolUserVerificationRequirement;
};

/**
 * ProtocolPublicKeyCredentialCreationOptionsPublic
 */
export type ProtocolPublicKeyCredentialCreationOptionsPublic = {
    [key: string]: unknown;
};

/**
 * ProtocolPublicKeyCredentialHints
 */
export enum ProtocolPublicKeyCredentialHints {
    /**
     * PublicKeyCredentialHintSecurityKey
     *
     * authenticatorAttachment SHOULD be set to cross-platform.
     */
    PUBLIC_KEY_CREDENTIAL_HINT_SECURITY_KEY = 'security-key',
    /**
     * PublicKeyCredentialHintClientDevice
     *
     * authenticatorAttachment SHOULD be set to platform.
     */
    PUBLIC_KEY_CREDENTIAL_HINT_CLIENT_DEVICE = 'client-device',
    /**
     * PublicKeyCredentialHintHybrid
     *
     * authenticatorAttachment SHOULD be set to cross-platform.
     */
    PUBLIC_KEY_CREDENTIAL_HINT_HYBRID = 'hybrid'
}

/**
 * ProtocolResidentKeyRequirement
 */
export enum ProtocolResidentKeyRequirement {
    /**
     * ResidentKeyRequirementDiscouraged
     *
     * accept a client-side discoverable credential. This is the default.
     */
    RESIDENT_KEY_REQUIREMENT_DISCOURAGED = 'discouraged',
    /**
     * ResidentKeyRequirementPreferred
     *
     * ResidentKeyRequirementPreferred indicates to the client we would prefer a discoverable credential.
     */
    RESIDENT_KEY_REQUIREMENT_PREFERRED = 'preferred',
    /**
     * ResidentKeyRequirementRequired
     *
     * prepared to receive an error if a client-side discoverable credential cannot be created.
     */
    RESIDENT_KEY_REQUIREMENT_REQUIRED = 'required'
}

/**
 * ProtocolURLEncodedBase64
 */
export type ProtocolUrlEncodedBase64 = {
    [key: string]: unknown;
};

/**
 * ProtocolUserVerificationRequirement
 */
export enum ProtocolUserVerificationRequirement {
    /**
     * VerificationRequired
     *
     * VerificationRequired User verification is required to create/release a credential.
     */
    VERIFICATION_REQUIRED = 'required',
    /**
     * VerificationPreferred
     *
     * This is the default.
     */
    VERIFICATION_PREFERRED = 'preferred',
    /**
     * VerificationDiscouraged
     *
     * VerificationDiscouraged The authenticator should not verify the user for the credential.
     */
    VERIFICATION_DISCOURAGED = 'discouraged'
}

/**
 * ResponseErrorResponse
 */
export type ErrorResponse = {
    data?: unknown;
    error: string;
    success: boolean;
};

/**
 * ResponseErrorResponsePublic
 */
export type ErrorResponsePublic = {
    [key: string]: unknown;
};

/**
 * ResponseSuccessResponse
 */
export type SuccessResponse = {
    data: unknown;
    error?: string;
    success: boolean;
};

/**
 * ResponseSuccessResponsePublic
 */
export type SuccessResponsePublic = {
    [key: string]: unknown;
};

/**
 * TypesURN
 */
export type TypesUrn = {
    [key: string]: unknown;
};

/**
 * WebauthncoseCOSEAlgorithmIdentifier
 */
export enum WebauthncoseCoseAlgorithmIdentifier {
    /**
     * AlgES256
     *
     * AlgES256 ECDSA with SHA-256.
     */
    ALG_ES256 = -7,
    /**
     * AlgEdDSA
     *
     * AlgEdDSA EdDSA.
     */
    ALG_ED_DSA = -8,
    /**
     * AlgES384
     *
     * AlgES384 ECDSA with SHA-384.
     */
    ALG_ES384 = -35,
    /**
     * AlgES512
     *
     * AlgES512 ECDSA with SHA-512.
     */
    ALG_ES512 = -36,
    /**
     * AlgPS256
     *
     * AlgPS256 RSASSA-PSS with SHA-256.
     */
    ALG_PS256 = -37,
    /**
     * AlgPS384
     *
     * AlgPS384 RSASSA-PSS with SHA-384.
     */
    ALG_PS384 = -38,
    /**
     * AlgPS512
     *
     * AlgPS512 RSASSA-PSS with SHA-512.
     */
    ALG_PS512 = -39,
    /**
     * AlgES256K
     *
     * AlgES256K is ECDSA using secp256k1 curve and SHA-256.
     */
    ALG_ES256K = -47,
    /**
     * AlgRS256
     *
     * AlgRS256 RSASSA-PKCS1-v1_5 with SHA-256.
     */
    ALG_RS256 = -257,
    /**
     * AlgRS384
     *
     * AlgRS384 RSASSA-PKCS1-v1_5 with SHA-384.
     */
    ALG_RS384 = -258,
    /**
     * AlgRS512
     *
     * AlgRS512 RSASSA-PKCS1-v1_5 with SHA-512.
     */
    ALG_RS512 = -259,
    /**
     * AlgRS1
     *
     * AlgRS1 RSASSA-PKCS1-v1_5 with SHA-1.
     */
    ALG_RS1 = -65535
}

export type RequestGetAccount = {
    body?: never;
    path?: never;
    query?: {
        /**
         * search by q
         */
        q?: string;
        /**
         * limit results
         */
        limit?: number;
        /**
         * offset results
         */
        offset?: number;
        /**
         * sort results e.g. 'created_at desc'
         */
        order?: string;
        /**
         * filters, see readme
         */
        filters?: string;
    };
    url: '/account';
};

export type GetAccountErrors = {
    /**
     * OK
     */
    400: ErrorResponse;
    /**
     * OK
     */
    404: ErrorResponse;
    /**
     * OK
     */
    500: ErrorResponse;
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type ResponseGetAccount = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: Array<AccountGenAccountJoinedPublic>;
    };
};

export type GetAccountResponse = ResponseGetAccount[keyof ResponseGetAccount];

export type RequestPostAccount = {
    /**
     * Account Data
     */
    body: AccountGenAccountPublic;
    path?: never;
    query?: never;
    url: '/account/';
};

export type PostAccountErrors = {
    /**
     * OK
     */
    400: ErrorResponse;
    /**
     * OK
     */
    404: ErrorResponse;
    /**
     * OK
     */
    500: ErrorResponse;
};

export type PostAccountError = PostAccountErrors[keyof PostAccountErrors];

export type ResponsePostAccount = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AccountGenAccountPublic;
    };
};

export type PostAccountResponse = ResponsePostAccount[keyof ResponsePostAccount];

export type RequestGetAccountById = {
    body?: never;
    path: {
        /**
         * Account ID
         */
        id: string;
    };
    query?: never;
    url: '/account/{id}';
};

export type GetAccountByIdErrors = {
    /**
     * OK
     */
    400: ErrorResponse;
    /**
     * OK
     */
    404: ErrorResponse;
    /**
     * OK
     */
    500: ErrorResponse;
};

export type GetAccountByIdError = GetAccountByIdErrors[keyof GetAccountByIdErrors];

export type ResponseGetAccountById = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AccountGenAccountJoinedPublic;
    };
};

export type GetAccountByIdResponse = ResponseGetAccountById[keyof ResponseGetAccountById];

export type RequestPutAccountById = {
    /**
     * Account Data
     */
    body: AccountGenAccountPublic;
    path: {
        /**
         * Account ID
         */
        id: string;
    };
    query?: never;
    url: '/account/{id}';
};

export type PutAccountByIdErrors = {
    /**
     * OK
     */
    400: ErrorResponse;
    /**
     * OK
     */
    404: ErrorResponse;
    /**
     * OK
     */
    500: ErrorResponse;
};

export type PutAccountByIdError = PutAccountByIdErrors[keyof PutAccountByIdErrors];

export type ResponsePutAccountById = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AccountGenAccountPublic;
    };
};

export type PutAccountByIdResponse = ResponsePutAccountById[keyof ResponsePutAccountById];

export type RequestGetAdminAccount = {
    body?: never;
    path?: never;
    query?: {
        /**
         * search by q
         */
        q?: string;
        /**
         * limit results
         */
        limit?: number;
        /**
         * offset results
         */
        offset?: number;
        /**
         * sort results e.g. 'created_at desc'
         */
        order?: string;
        /**
         * filters, see readme
         */
        filters?: string;
    };
    url: '/admin/account';
};

export type GetAdminAccountErrors = {
    /**
     * OK
     */
    400: ErrorResponse;
    /**
     * OK
     */
    404: ErrorResponse;
    /**
     * OK
     */
    500: ErrorResponse;
};

export type GetAdminAccountError = GetAdminAccountErrors[keyof GetAdminAccountErrors];

export type ResponseGetAdminAccount = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: Array<AccountGenAccountJoined>;
    };
};

export type GetAdminAccountResponse = ResponseGetAdminAccount[keyof ResponseGetAdminAccount];

export type RequestPostAdminAccount = {
    /**
     * Account Data
     */
    body: AccountGenAccount;
    path?: never;
    query?: never;
    url: '/admin/account/';
};

export type PostAdminAccountErrors = {
    /**
     * OK
     */
    400: ErrorResponse;
    /**
     * OK
     */
    404: ErrorResponse;
    /**
     * OK
     */
    500: ErrorResponse;
};

export type PostAdminAccountError = PostAdminAccountErrors[keyof PostAdminAccountErrors];

export type ResponsePostAdminAccount = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AccountGenAccount;
    };
};

export type PostAdminAccountResponse = ResponsePostAdminAccount[keyof ResponsePostAdminAccount];

export type RequestGetAdminAccountCount = {
    body?: never;
    path?: never;
    query?: {
        /**
         * search by q
         */
        q?: string;
        /**
         * filters, see readme
         */
        filters?: string;
    };
    url: '/admin/account/count';
};

export type GetAdminAccountCountErrors = {
    /**
     * OK
     */
    400: ErrorResponse;
    /**
     * OK
     */
    404: ErrorResponse;
    /**
     * OK
     */
    500: ErrorResponse;
};

export type GetAdminAccountCountError = GetAdminAccountCountErrors[keyof GetAdminAccountCountErrors];

export type ResponseGetAdminAccountCount = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: number;
    };
};

export type GetAdminAccountCountResponse = ResponseGetAdminAccountCount[keyof ResponseGetAdminAccountCount];

export type RequestGetAdminAccountById = {
    body?: never;
    path: {
        /**
         * Account ID
         */
        id: string;
    };
    query?: never;
    url: '/admin/account/{id}';
};

export type GetAdminAccountByIdErrors = {
    /**
     * OK
     */
    400: ErrorResponse;
    /**
     * OK
     */
    404: ErrorResponse;
    /**
     * OK
     */
    500: ErrorResponse;
};

export type GetAdminAccountByIdError = GetAdminAccountByIdErrors[keyof GetAdminAccountByIdErrors];

export type ResponseGetAdminAccountById = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AccountGenAccountJoined;
    };
};

export type GetAdminAccountByIdResponse = ResponseGetAdminAccountById[keyof ResponseGetAdminAccountById];

export type RequestPutAdminAccountById = {
    /**
     * Account Data
     */
    body: AccountGenAccount;
    path: {
        /**
         * Account ID
         */
        id: string;
    };
    query?: never;
    url: '/admin/account/{id}';
};

export type PutAdminAccountByIdErrors = {
    /**
     * OK
     */
    400: ErrorResponse;
    /**
     * OK
     */
    404: ErrorResponse;
    /**
     * OK
     */
    500: ErrorResponse;
};

export type PutAdminAccountByIdError = PutAdminAccountByIdErrors[keyof PutAdminAccountByIdErrors];

export type ResponsePutAdminAccountById = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AccountGenAccount;
    };
};

export type PutAdminAccountByIdResponse = ResponsePutAdminAccountById[keyof ResponsePutAdminAccountById];

export type RequestPostAdminTestUser = {
    body?: never;
    path?: never;
    query?: {
        /**
         * name search by q
         */
        q?: string;
    };
    url: '/admin/testUser';
};

export type PostAdminTestUserErrors = {
    /**
     * OK
     */
    400: ErrorResponse;
    /**
     * OK
     */
    404: ErrorResponse;
    /**
     * OK
     */
    500: ErrorResponse;
};

export type PostAdminTestUserError = PostAdminTestUserErrors[keyof PostAdminTestUserErrors];

export type ResponsePostAdminTestUser = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: Array<AccountGenAccount>;
    };
};

export type PostAdminTestUserResponse = ResponsePostAdminTestUser[keyof ResponsePostAdminTestUser];

export type RequestPostAuth2FaDisable = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/2fa/disable';
};

export type PostAuth2FaDisableErrors = {
    /**
     * OK
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type PostAuth2FaDisableError = PostAuth2FaDisableErrors[keyof PostAuth2FaDisableErrors];

export type ResponsePostAuth2FaDisable = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: boolean;
    };
};

export type PostAuth2FaDisableResponse = ResponsePostAuth2FaDisable[keyof ResponsePostAuth2FaDisable];

export type RequestPostAuth2FaEnable = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/2fa/enable';
};

export type PostAuth2FaEnableErrors = {
    /**
     * Bad Request - no 2FA method set up
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type PostAuth2FaEnableError = PostAuth2FaEnableErrors[keyof PostAuth2FaEnableErrors];

export type ResponsePostAuth2FaEnable = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: boolean;
    };
};

export type PostAuth2FaEnableResponse = ResponsePostAuth2FaEnable[keyof ResponsePostAuth2FaEnable];

export type RequestPostAuth2FaInitiate = {
    /**
     * authentication_method_id of the 2FA method to challenge
     */
    body: AuthInitiateTwoFaRequest;
    path?: never;
    query?: never;
    url: '/auth/2fa/initiate';
};

export type PostAuth2FaInitiateErrors = {
    /**
     * Bad Request - authentication method required
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type PostAuth2FaInitiateError = PostAuth2FaInitiateErrors[keyof PostAuth2FaInitiateErrors];

export type ResponsePostAuth2FaInitiate = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AuthServiceAuthChallengePublic;
    };
};

export type PostAuth2FaInitiateResponse = ResponsePostAuth2FaInitiate[keyof ResponsePostAuth2FaInitiate];

export type RequestGetAuth2FaMethods = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/2fa/methods';
};

export type GetAuth2FaMethodsErrors = {
    /**
     * OK
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type GetAuth2FaMethodsError = GetAuth2FaMethodsErrors[keyof GetAuth2FaMethodsErrors];

export type ResponseGetAuth2FaMethods = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: Array<AuthenticationMethodPublic>;
    };
};

export type GetAuth2FaMethodsResponse = ResponseGetAuth2FaMethods[keyof ResponseGetAuth2FaMethods];

export type RequestPostAuth2FaValidated = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/2fa/validated';
};

export type PostAuth2FaValidatedErrors = {
    /**
     * OK
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type PostAuth2FaValidatedError = PostAuth2FaValidatedErrors[keyof PostAuth2FaValidatedErrors];

export type ResponsePostAuth2FaValidated = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: boolean;
    };
};

export type PostAuth2FaValidatedResponse = ResponsePostAuth2FaValidated[keyof ResponsePostAuth2FaValidated];

export type RequestPostAuth2FaVerify = {
    /**
     * Verification parameters including challenge_id and method-specific response
     */
    body: AuthServiceVerifyAuthParams;
    path?: never;
    query?: never;
    url: '/auth/2fa/verify';
};

export type PostAuth2FaVerifyErrors = {
    /**
     * OK
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type PostAuth2FaVerifyError = PostAuth2FaVerifyErrors[keyof PostAuth2FaVerifyErrors];

export type ResponsePostAuth2FaVerify = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AuthVerifyResponsePublic;
    };
};

export type PostAuth2FaVerifyResponse = ResponsePostAuth2FaVerify[keyof ResponsePostAuth2FaVerify];

export type RequestPostAuthInitiate = {
    /**
     * Authentication parameters
     */
    body: AuthServiceInitiateAuthParams;
    path?: never;
    query?: never;
    url: '/auth/initiate';
};

export type PostAuthInitiateErrors = {
    /**
     * OK
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type PostAuthInitiateError = PostAuthInitiateErrors[keyof PostAuthInitiateErrors];

export type ResponsePostAuthInitiate = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AuthServiceAuthChallengePublic;
    };
};

export type PostAuthInitiateResponse = ResponsePostAuthInitiate[keyof ResponsePostAuthInitiate];

export type RequestPostAuthMethods = {
    /**
     * User identifier (email, phone, etc.)
     */
    body: AuthMethodsInput;
    path?: never;
    query?: never;
    url: '/auth/methods';
};

export type PostAuthMethodsErrors = {
    /**
     * OK
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type PostAuthMethodsError = PostAuthMethodsErrors[keyof PostAuthMethodsErrors];

export type ResponsePostAuthMethods = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AuthGetMethodsResponsePublic;
    };
};

export type PostAuthMethodsResponse = ResponsePostAuthMethods[keyof ResponsePostAuthMethods];

export type RequestPostAuthPasswordSet = {
    /**
     * Password data including current password (if exists) and new password with confirmation
     */
    body: AuthPasswordPostData;
    path?: never;
    query?: never;
    url: '/auth/password/set';
};

export type PostAuthPasswordSetErrors = {
    /**
     * Bad Request - passwords don't match, current password incorrect, or missing primary email
     */
    400: ErrorResponsePublic;
    /**
     * Not Found
     */
    404: ErrorResponsePublic;
    /**
     * Internal Server Error
     */
    500: ErrorResponsePublic;
};

export type PostAuthPasswordSetError = PostAuthPasswordSetErrors[keyof PostAuthPasswordSetErrors];

export type ResponsePostAuthPasswordSet = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AuthenticationMethodPublic;
    };
};

export type PostAuthPasswordSetResponse = ResponsePostAuthPasswordSet[keyof ResponsePostAuthPasswordSet];

export type RequestPostAuthRegistration = {
    /**
     * Registration parameters including auth_type and identifier
     */
    body: AuthServiceInitiateAuthParams;
    path?: never;
    query?: never;
    url: '/auth/registration';
};

export type PostAuthRegistrationErrors = {
    /**
     * Bad Request - invalid method or missing identifier
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type PostAuthRegistrationError = PostAuthRegistrationErrors[keyof PostAuthRegistrationErrors];

export type ResponsePostAuthRegistration = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AuthInitiateRegisterResponsePublic;
    };
};

export type PostAuthRegistrationResponse = ResponsePostAuthRegistration[keyof ResponsePostAuthRegistration];

export type RequestGetAuthRegistrationQrcodeByChallengeId = {
    body?: never;
    path: {
        /**
         * Registration challenge ID
         */
        challenge_id: string;
    };
    query?: never;
    url: '/auth/registration/qrcode/{challenge_id}';
};

export type GetAuthRegistrationQrcodeByChallengeIdErrors = {
    /**
     * Invalid challenge ID
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type GetAuthRegistrationQrcodeByChallengeIdError = GetAuthRegistrationQrcodeByChallengeIdErrors[keyof GetAuthRegistrationQrcodeByChallengeIdErrors];

export type ResponseGetAuthRegistrationQrcodeByChallengeId = {
    /**
     * QR code PNG image
     */
    200: unknown;
};

export type RequestPostAuthRegistrationVerify = {
    /**
     * Verification parameters including challenge_id and auth_type
     */
    body: AuthServiceVerifyAuthParams;
    path?: never;
    query?: never;
    url: '/auth/registration/verify';
};

export type PostAuthRegistrationVerifyErrors = {
    /**
     * Bad Request - missing challenge_id or auth_type
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type PostAuthRegistrationVerifyError = PostAuthRegistrationVerifyErrors[keyof PostAuthRegistrationVerifyErrors];

export type ResponsePostAuthRegistrationVerify = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AuthenticationMethodPublic;
    };
};

export type PostAuthRegistrationVerifyResponse = ResponsePostAuthRegistrationVerify[keyof ResponsePostAuthRegistrationVerify];

export type RequestDeleteAuthRegistrationById = {
    body?: never;
    path: {
        /**
         * AuthenticationMethod ID
         */
        id: string;
    };
    query?: never;
    url: '/auth/registration/{id}';
};

export type DeleteAuthRegistrationByIdErrors = {
    /**
     * OK
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type DeleteAuthRegistrationByIdError = DeleteAuthRegistrationByIdErrors[keyof DeleteAuthRegistrationByIdErrors];

export type ResponseDeleteAuthRegistrationById = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: boolean;
    };
};

export type DeleteAuthRegistrationByIdResponse = ResponseDeleteAuthRegistrationById[keyof ResponseDeleteAuthRegistrationById];

export type RequestPostAuthVerify = {
    /**
     * Verification parameters including challenge_id and method-specific response
     */
    body: AuthServiceVerifyAuthParams;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type PostAuthVerifyErrors = {
    /**
     * OK
     */
    400: ErrorResponsePublic;
    /**
     * OK
     */
    401: ErrorResponsePublic;
    /**
     * OK
     */
    404: ErrorResponsePublic;
    /**
     * OK
     */
    500: ErrorResponsePublic;
};

export type PostAuthVerifyError = PostAuthVerifyErrors[keyof PostAuthVerifyErrors];

export type ResponsePostAuthVerify = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AuthVerifyResponsePublic;
    };
};

export type PostAuthVerifyResponse = ResponsePostAuthVerify[keyof ResponsePostAuthVerify];

export type RequestGetMe = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type GetMeErrors = {
    /**
     * OK
     */
    400: ErrorResponse;
    /**
     * OK
     */
    404: ErrorResponse;
    /**
     * OK
     */
    500: ErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type ResponseGetMe = {
    /**
     * OK
     */
    200: SuccessResponse & {
        data?: AccountGenAccountWithFeaturesPublic;
    };
};

export type GetMeResponse = ResponseGetMe[keyof ResponseGetMe];
