export type StoreKeys =
  | "admin"
  | "account"
  | "category"
  | "asset"
  | "client"
  | "company"
  | "facility"
  | "industry"
  | "manufacturer"
  | "organization"
  | "opportunity"
  | "pipeline"
  | "request"
  | "global_config"
  | "change_log";
